doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            client_id: 'App\Shipping\Infrastructure\Mapping\Type\ClientIdType'
            shipping_address_list: 'App\Shipping\Infrastructure\Mapping\Type\ShippingAddressListType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Client:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shipping/Infrastructure/Mapping'
                prefix: 'App\Shipping\Domain\Model'
                alias: Client
